version: "3.5"
services:
  auth_app:
    build: .
    container_name: cdslab_auth_app
    env_file: .env
    image: fenfisdi/cdslab_auth:dev
    networks:
      - cdslab_auth
    ports:
      - 8080:8080
    volumes:
    - ./src:/app/src


networks:
  cdslab_auth:
    name: cdslab_auth
    driver: bridge