# Package setup

from setuptools import find_packages, setup

with open('README.md', 'r') as readme_file:
    long_description = readme_file.read()

setup(
    name='cdslab_auth',
    version='0.0.1',
    maintainer='Developers of the CDS team of FEnFiSDi group',
    maintainer_email='alejandro.campillo@udea.edu.co',
    description='Authentication API for CDSLab',
    long_description=long_description,
    url='https://github.com/fenfisdi/cdslab_auth',
    author='Alejandro Campillo',
    author_email='alejandro.campillo@udea.edu.co',
    license='GNU General Public License v3 (GPLv3)',
    classifiers=[
        'Development Status :: 1 - Planning',
        'Framework :: CDSLab',
        'Intended Audience :: Science/Research',
        'Intended Audience :: Education',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
        'Natural Language :: English',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: Implementation :: CPython',
        'Topic :: Education',
        'Topic :: Scientific/Engineering :: Medical Science Apps.',
        'Topic :: Software Development',
        'Topic :: Software Development :: Libraries'
        ],
    test_suite='pytest',
    packages=find_packages(exclude='__pycache__'),
    keywords=[
        'Computation',
        'Authentication',
        'Security',
        '2FA'
        ],
    python_requires='>=3.8',
    install_requires=[
        "python=3.8",
        "Jinja2=2.11.2",
        "MarkupSafe=1.1.1",
        "Pillow=8.0.0",
        "atomicwrites=1.4.0",
        "attrs=20.3.0",
        "bcrypt=3.2.0",
        "cffi=1.14.5",
        "click=7.1.2",
        "colorama=0.4.4",
        "dnspython=2.1.0",
        "ecdsa=0.16.1",
        "email-validator=1.1.2",
        "fastapi=0.63.0",
        "h11=0.12.0",
        "idna=3.1",
        "iniconfig=1.1.1",
        "json-cfg=0.4.2",
        "kwonly-args=1.0.10",
        "packaging=20.9",
        "passlib=1.7.4",
        "phonenumbers=8.10.14",
        "pluggy=0.13.1",
        "py=1.10.0",
        "pyasn1=0.4.8",
        "pycparser=2.20",
        "pydantic=1.8.1",
        "pymongo=3.11.0",
        "pyotp=2.6.0",
        "pyparsing=2.4.7",
        "pytest=6.1.1",
        "python-dotenv=0.15.0",
        "python-jose=3.1.0",
        "python-multipart=0.0.5",
        "qrcode=6.1",
        "rsa=4.7.2",
        "six=1.15.0",
        "starlette=0.13.6",
        "toml=0.10.2",
        "typing-extensions=3.7.4.3",
        "uvicorn=0.13.3"
        ],
    zip_safe=False
    )
