from fastapi import APIRouter
from models import user
from uses_cases.auth_cases import validation_login_auth, validation_qr_auth, generate_refresh_token
import pyotp
from pprint import pprint
router = APIRouter()


@router.post("/loginAuthentication")
async def login_auth(user: user.auth_in):
    """
    validates user login

    Parameters
    ----------
    - user: dict
            A string email
    Returns
    ----------
    - **response** : dict
        - key_qr: string 
                The key_qr is the hash key generated by the pyotp plugin that will help us to match the second authentication factor.

        - email:string
                This property refers to the user's email address

    Raises
    ----------
    - **HTTPException**
            If the password not is equal
    - **HTTPException**
            If user not exist

    """
    is_login = validation_login_auth(user)
    return is_login


@router.post("/qrAuthentication")
async def qr_auth(user: user.two_auth_in):
    """
    validates the value of the qr with the value entered by the user
    and generate the token

    Parameters
    ----------
    - email: str
            A string email

    - qr_value: int
            A int user-typed value
    Returns
    ----------
    - **response** : string
            token

    Raises
    ----------
    - **HTTPException**
            If the token is invalid or the email key doesn´t exist
    - **HTTPException**
            If incorret key_qr value

    """

    is_auth = validation_qr_auth(user.email, user.qr_value)
    return is_auth


@router.post("/refreshAuthentication")
async def refresh_auth(user: user.auth_refresh):
    """
     generates a new token to the user

     Parameters
     ----------
     - email: str
             A string email

     - key_qr: str
             Is a str value of the key_qr stored in BD
     Returns
     ----------
     - **response** : string
             token

     Raises
     ----------
     - **HTTPException**
             If the library is unable to generate the token
     - **HTTPException**
             If incorret key_qr value

     """
    return generate_refresh_token(user.key_qr)
